// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbPX9Y6y6OLNiYrj-3m1Cqp0nwImY3GjI',
    appId: '1:949829844688:web:e68d0822d67196d5aaa8d5',
    messagingSenderId: '949829844688',
    projectId: 'mwhatsapp-2e608',
    authDomain: 'mwhatsapp-2e608.firebaseapp.com',
    storageBucket: 'mwhatsapp-2e608.firebasestorage.app',
    measurementId: 'G-0173ZM8CNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChTKCjNyco4V04Zf2mn4VYQkhYjY8-nPU',
    appId: '1:949829844688:android:2349e101899a8cf7aaa8d5',
    messagingSenderId: '949829844688',
    projectId: 'mwhatsapp-2e608',
    storageBucket: 'mwhatsapp-2e608.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0y_CCEfsx0V2mpoQ-XRqFZgO8hxe6gN0',
    appId: '1:949829844688:ios:b912d4d0f66176baaaa8d5',
    messagingSenderId: '949829844688',
    projectId: 'mwhatsapp-2e608',
    storageBucket: 'mwhatsapp-2e608.firebasestorage.app',
    iosBundleId: 'com.example.mwhatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0y_CCEfsx0V2mpoQ-XRqFZgO8hxe6gN0',
    appId: '1:949829844688:ios:b912d4d0f66176baaaa8d5',
    messagingSenderId: '949829844688',
    projectId: 'mwhatsapp-2e608',
    storageBucket: 'mwhatsapp-2e608.firebasestorage.app',
    iosBundleId: 'com.example.mwhatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbPX9Y6y6OLNiYrj-3m1Cqp0nwImY3GjI',
    appId: '1:949829844688:web:800d755a29ae2727aaa8d5',
    messagingSenderId: '949829844688',
    projectId: 'mwhatsapp-2e608',
    authDomain: 'mwhatsapp-2e608.firebaseapp.com',
    storageBucket: 'mwhatsapp-2e608.firebasestorage.app',
    measurementId: 'G-WQGBCJY011',
  );

}